### ISSUE TITLE
Output stripped binary

### ISSUE THREAD

**Issue by jonjove** [stellar/soroban-token-contract#30]
### What problem does your feature solve?

This contract gets embedded in other contracts, so having a stripped version will be helpful.

### What would you like to see?

A new `target-tiny-stripped` directory with the output from `wasm-strip`.

### What alternatives are there?

N/A

**Comment by leighmcculloch** [comment]
`wasm-strip` removes sections from a wasm file. Which sections are you imagining we should remove from the token contract?

**Comment by jonjove** [comment]
I think it's possible that people writing factory contracts will not want to include the contract spec in every deployment. For example, in this contract the contract spec is about 20% of the total size.

In past discussions, we have also mentioned that we might require contracts to be stripped (or at least partially stripped) before they can be deployed. I'm not sure if we still are thinking in that direction.

**Comment by leighmcculloch** [comment]
It's unclear if we want to do this, and I think we can revisit this as part of a general performance consideration review.
