### ISSUE TITLE
Expose common functionality

### ISSUE THREAD

**Issue by sisuresh** [stellar/soroban-token-contract#31]
Some of the functionality in the token contract has been copied into the liquidity pool and single offer asset sale contracts. For example, `sign_ed25519_then_do` exists in all three contracts. The token contract should expose anything useful for downstream contracts to avoid copying code.

**Comment by jonjove** [comment]
This is currently blocked by our working simplifying authorization, as noted https://github.com/stellar/soroban-token-contract/pull/79#issuecomment-1209531576.

**Comment by sisuresh** [comment]
Resolved by https://github.com/stellar/soroban-examples/pull/76
