### ISSUE TITLE
Implement wrapper interface

### ISSUE THREAD

**Issue by jonjove** [stellar/soroban-token-contract#5]

**Comment by jonjove** [comment]
Blocked by https://github.com/stellar/rs-stellar-contract-env/issues/175 because it will depend on host functions that are only enabled for native contracts

**Comment by jonjove** [comment]
Blocked by https://github.com/stellar/rs-soroban-env/issues/316

**Comment by smac711** [comment]
@jonjove is this issue still in progress or are you blocked now since you commented a month back saying env#316 is blocking you?

**Comment by jonjove** [comment]
This is actually done, follow up work in https://github.com/stellar/rs-soroban-env/issues/428.

**Comment by smac711** [comment]
Thank you for the confirmation 🥂
