### ISSUE TITLE
Change domain to Symbol

### ISSUE THREAD

**Issue by jonjove** [stellar/soroban-token-contract#81]
See https://github.com/stellar/rs-soroban-sdk/issues/399#issuecomment-1208583096 and https://github.com/stellar/rs-soroban-sdk/issues/399#issuecomment-1208635802

**Comment by sisuresh** [comment]
We need to expose the current contract function name in the host crate for this right? Something similar to `get_current_contract`?

**Comment by leighmcculloch** [comment]
Contracts should know what their function is that's being executed, so I'm not sure it is strictly needed. Is there a case where it isn't naturally known?

If it's needed, maybe something like `get_current_contract_function_name`.

**Comment by jonjove** [comment]
Agreed, the contract knows what function is being executed so there is no need to get this information from the host.

**Comment by sisuresh** [comment]
Are you saying I should update the macros so the [current method](https://github.com/stellar/rs-soroban-sdk/blob/2e0214c456b85d2c3702970a90dfcfae0b704374/soroban-sdk-macros/src/derive_fn.rs#L274) is stored? Or is something similar already implemented?

**Comment by jonjove** [comment]
@sisuresh I don't think I understand what you're proposing? To clarify what I meant above, consider the `xfer` function. When it checks signatures now, it knows to use `Domain::Transfer`. In this proposal, it would use `Symbol::from_symbol("xfer")`. Every function is already choosing the domain, so there's no reason they can't construct the appropriate symbol instead.

**Comment by sisuresh** [comment]
Ah yeah we weren't on the same page. I was discussing deriving the function name, but you're right we don't need to do that.

**Comment by sisuresh** [comment]
The [Authorization](https://github.com/stellar/soroban-examples/tree/dev/authorization) example uses a Symbol.

**Comment by sisuresh** [comment]
Resolved in https://github.com/stellar/soroban-token-contract/pull/86.
